feat!: update models to cat-vrs 1.0.0 trial review ballot
ga4gh/cat-vrs-python pull request #9
Opened 2024-12-19 13:44 UTC by korikuzma

close #8 

* Update models to cat-vrs [1.0.0-ballot.2024-11.2](https://github.com/ga4gh/cat-vrs/tree/1.0.0-ballot.2024-11.2) tag

2024-12-19 13:46 UTC, korikuzma commented
Probably good for me to add some tests for the recipe validators

2024-12-23 19:36 UTC, korikuzma commented
@brendanreardon Would like your review too

2024-12-23 19:37 UTC, korikuzma commented on src/ga4gh/cat_vrs/recipes.py
> +        :raises ValueError: If constraints property does not satisfy the requirements
@brendanreardon @DanielPuthawala do you like this approach or would you rather make all checks and list ALL validation errors at once?

2025-01-02 18:52 UTC, brendanreardon commented on src/ga4gh/cat_vrs/recipes.py
> +        :raises ValueError: If constraints property does not satisfy the requirements
This is so cool!! Thank you, @korikuzma! 

This makes sense to me, and I think that it is preferable to list the validation errors as they come to enhance tracebackability (this that a word?).

2025-01-02 18:54 UTC, brendanreardon commented
> @brendanreardon Would like your review too

Aye, aye! Once I get back into building out examples, I'll try running the current recipes through your code here.

2025-01-06 14:43 UTC, korikuzma commented on src/ga4gh/cat_vrs/recipes.py
> +        :raises ValueError: If constraints property does not satisfy the requirements
Okay, we can always change in a future version if we want to list all errors at once (which is nice for development)

2025-01-06 14:49 UTC, brendanreardon commented on src/ga4gh/cat_vrs/recipes.py
> +        :raises ValueError: If constraints property does not satisfy the requirements
Ah gotcha. In that case since the latter is better for development, I totally defer to you!

2025-01-06 17:24 UTC, korikuzma commented on src/ga4gh/cat_vrs/recipes.py
> +        :raises ValueError: If constraints property does not satisfy the requirements
Okay, let's leave it as is for now (to be consistent with VRS-Python too).

2025-01-14 15:14 UTC, DanielPuthawala approved these changes
Looks good.  we talked through the changes earlier, I jst forgot to come back on and submit my review.

2025-01-14 17:40 UTC, korikuzma commented on src/ga4gh/cat_vrs/models.py
@DanielPuthawala I don't think I'm following... Can you rephrase?

2025-01-14 17:57 UTC, DanielPuthawala commented on src/ga4gh/cat_vrs/models.py
That was a question I had before about constraints haveng an explicit enum of relations to instead having just a slot for relations and having the actual list elsewhere (in GKS:core).

You and I later on discussed this, and decided it wasn't something we had to address for this PR.

2025-01-14 19:04 UTC, korikuzma commented on src/ga4gh/cat_vrs/models.py
Ah okay. Thank you

2025-01-22 17:44 UTC, brendanreardon requested changes
Thank you for this, @korikuzma !! @DanielPuthawala may need to look over these pieces of feedback

2025-01-22 17:44 UTC, brendanreardon commented on src/ga4gh/cat_vrs/recipes.py
> +        constraint = v[0]
Here, this presumes that the list of constraints is of length 1. Should there be a similar "if not" statement checking the length of the `list[Constraint]` input? e.g.,

```python
if not len(v) == 1:
	err_msg = "CanonicalAllele requires a minimum and maximum of 1 constraint"
	raise ValueError(err_msg)
```

Without this error check, users could pass a list of constraints for a canonical allele and this function will only check the first constraint. 

With that said, this will _probably_ be changed in a future branch per adding FeatureContextConstraint.

2025-01-22 17:44 UTC, brendanreardon commented on src/ga4gh/cat_vrs/recipes.py
> +        Each constraint in ``constraints`` must satisfy ALL of the following
This docstring does not fully reflect the schema for [CategoricalCnv](https://github.com/ga4gh/cat-vrs/blob/1.0.0-ballot.2024-11/schema/cat-vrs/recipes-source.yaml#L70-L97), I think. In particular, the requirements specified here apply to `constraints` / `v`, not each constraint in `constraints`.

If so, this docstring should instead say
```
``constraints`` must contain two constraints that satisfy ALL of the following requirements, respectively:
```

This could alternatively read
```
``constraints`` must contain two constraints - ``DefiningLocationConstraint`` and either ``CopyCountConstraint`` or ``CopyChangeCount`` - that satisfy ALL of the following requirements, respectively:
```

but I think that this second one seems to be more against the style that these docstrings have been written.

2025-01-22 17:44 UTC, brendanreardon commented on src/ga4gh/cat_vrs/recipes.py
> +        def_loc_constr_found = False
The error handling for `DefiningLocationConstraint` can be made more granular, similar to `CanonicalAllele` by doing something like the code below. At the moment, there is only one error message for DefiningLocationConstraint, regardless of if the relation requirement is satisfied. You can totally imagine some poor developer head banging at their desk thinking, "but I _am_ passing a DefiningLocationConstraint with the correct relations"... when maybe their relations are not set up properly.

```python
def_loc_constr_found = False  
def_loc_constr_valid = False
copy_constr_found = False  

for constraint in v:  
    constraint = constraint.root  
    if not def_loc_constr_found and isinstance(  
        constraint, DefiningLocationConstraint  
    ):  
	    def loc_constr_found = True
        for r in constraint.relations:  
            if (  
                r.primaryCode  
                and r.primaryCode.root == Relation.LIFTOVER_TO.value  
            ):  
                def_loc_constr_valid = True  
                continue  
    if not copy_constr_found:  
        copy_constr_found = isinstance(  
            constraint, CopyCountConstraint | CopyChangeConstraint  
        )  
  
if not def_loc_constr_found:  
    err_msg = f"Must contain a `DefiningLocationConstraint` with at least one relation where `primaryCode` is '{Relation.LIFTOVER_TO.value}'."  
    raise ValueError(err_msg)  

if not def_loc_constr_valid:
	err_msg = f"``DefiningLocationConstraint found``, but Must contain at least one relation where `primaryCode` is '{Relation.LIFTOVER_TO.value}'"
	raise ValueError(err_msg)

if not copy_constr_found:  
    err_msg = (  
        "Must contain either a `CopyCountConstraint` or `CopyChangeConstraint`."  
    )  
    raise ValueError(err_msg)
```

2025-01-22 17:44 UTC, brendanreardon commented on tests/validation/test_cat_vrs_models.py
> +                allele="allele.json#/1",
Does this refer to [Allele.json](https://github.com/ga4gh/vrs/blob/0106b48c1db0b420efd787cc769e4b35f415068e/schema/vrs/json/Allele) in vrs' schemas? If so, should this be capitalized?

2025-01-22 17:44 UTC, brendanreardon commented on tests/validation/test_cat_vrs_models.py
> +    invalid_params["constraints"] = [
This should instead be

```python
invalid_params["constraints"] = [
    copy_change_constr
]
```

right? This may also require some additional tests to make sure that either `CopyCountConstraint` or `CopyChangeConstraint`, whichever is passed, is valid.

2025-01-22 18:57 UTC, korikuzma commented on src/ga4gh/cat_vrs/recipes.py
> +        constraint = v[0]
@brendanreardon So in line 74 we have: `constraints: list[Constraint] = Field(..., min_length=1, max_length=1)` to ensure this list has a length of 1

2025-01-22 19:00 UTC, korikuzma commented on tests/validation/test_cat_vrs_models.py
> +                allele="allele.json#/1",
Oh, this was just a dummy IRI. I can make a comment

2025-01-22 19:08 UTC, korikuzma commented on tests/validation/test_cat_vrs_models.py
> +    invalid_params["constraints"] = [
I can update the comment to be clearer. This was testing that constraints does not contain either a `CopyCountConstraint` or a `CopyChangeConstraint`. 

The first two examples in `test_categorical_cnv` test valid input (either `CopyCountConstraint` or `CopyChangeConstraint`). I have tests for `CopyChangeConstrint` in `test_copy_change_constraint`, but can make tests for `CopyCountConstraint`.

2025-01-22 19:20 UTC, korikuzma commented on src/ga4gh/cat_vrs/recipes.py
> +        Each constraint in ``constraints`` must satisfy ALL of the following
@brendanreardon Updated. Let me know what you think

2025-01-22 19:31 UTC, korikuzma commented on src/ga4gh/cat_vrs/recipes.py
> +        def_loc_constr_found = False
Added!

2025-01-22 20:06 UTC, brendanreardon commented on src/ga4gh/cat_vrs/recipes.py
> +        Each constraint in ``constraints`` must satisfy ALL of the following
I love it! Thank you!

2025-01-22 20:32 UTC, brendanreardon commented on tests/validation/test_cat_vrs_models.py
> +    invalid_params["constraints"] = [
re: comment Ah!! Okay, I see now. Thank you! 

re: tests. that was so quick! thank you!

2025-01-22 20:33 UTC, brendanreardon commented on tests/validation/test_cat_vrs_models.py
> +def test_copy_count_constraint():
this looks great!

2025-01-22 20:34 UTC, brendanreardon approved these changes
🤜 🤛 this looks great! Sorry again for punting on this

2025-01-22 20:46 UTC, DanielPuthawala commented
Just caught up on your guys' back-and-forth.  It still looks good to me.  Are you going to squash and merge now, Kori?

2025-01-23 12:41 UTC, merged